# Generated by Django 5.2.17 on 2026-09-09 08:42

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1860), django.core.validators.MaxValueValidator(catalog.models.current_year_plus_one)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='catalog.artist')),
            ],
            options={
                'ordering': ['artist__name', 'release_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='catalog.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='catalog.song')),
            ],
            options={
                'ordering': ['album', 'track_number'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', through='catalog.AlbumSong', to='catalog.song'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album', 'track_number'), name='uniq_album_track_number'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album', 'song'), name='uniq_album_song'),
        ),
    ]
